# Generated by Django 4.2.1 on 2023-05-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('color', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productbadge'),
        ),
    ]
