# Generated by Django 4.2.1 on 2023-06-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('m', 'мужской'), ('w', 'женский')], default='m', max_length=1, verbose_name='пол'),
        ),
    ]
