# Generated by Django 4.2.1 on 2023-06-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(default='m', max_length=1, verbose_name='пол'),
        ),
    ]
